[workspace]
members = ["crates/*"]

[package]
name = "rust_sdl"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "crates/engine" }
engine_macros = { path = "crates/engine/macros" }